############################################### Time Series Model Parameters ##############################################
#model:
#  type: object
#  label: Model
#  fields:
#    - encoder
#    - decoder
#    - VQ-VAE
#    - MaskGIT
#MaskGIT:
#  type: object
#  label: Transformer
#  fields:
#    - prior_model_l
#    - prior_model_h
#prior_model_l:
#  type: object
#  label: Transformer_l
#  fields:
#    - hidden_dim#prior-model-low
#    - n_layers#prior-model-low
#    - heads#prior-model-low
#hidden_dim#prior-model-low:
#  type: number
#  label: Transformer hidden dimension
#  min: 128
#n_layers#prior-model-low:
#  type: number
#  label: Number of attention blocks
#  min: 4
#heads#prior-model-low:
#  type: number
#  label: Number of heads
#  min: 2
#
#prior_model_h:
#  type: object
#  label: Transformer_h
#  fields:
#    - hidden_dim#prior-model-high
#    - n_layers#prior-model-high
#    - heads#prior-model-high
#hidden_dim#prior-model-high:
#  type: number
#  label: Transformer hidden dimension
#  min: 32
#n_layers#prior-model-high:
#  type: number
#  label: Number of attention blocks
#  min: 1
#heads#prior-model-high:
#  type: number
#  label: Number of heads
#  min: 1

model:
  type: skipped

train:
  type: object
  label: Training
  fields:
    - gpu_device_id
    - seq_len
    - exp_params
    - trainer_params

exp_params:
  type: object
  label: Training hyper-parameters
  fields:
    - lr#maskgit-lr
lr#maskgit-lr:
  type: number
  label: Learning rate
  tags:
    - High Impact

gpu_device_id:
  type: number
  label: GPU idx
  min: 0

seq_len:
  type: number
  label: Length of one time-series data
  min: 1
  tags:
    - High Impact

trainer_params:
  type: object
  label: Training hyper-parameters
  fields:
    - max_steps
max_steps:
  type: object
  label: Training steps
  fields:
    - stage1
    - stage2
stage1:
  type: number
  label: Discreted VAE training steps
  min: 1
  tags:
    - High Impact
stage2:
  type: number
  label: Transformer training steps
  min: 1
  tags:
    - High Impact

generate:
  type: object
  label: Generation
  fields:
    - num_rows
    - evaluation

evaluation:
  type: object
  label: Generation batch size
  fields:
    - batch_size#generation

batch_size#generation:
  type: number
  label: Batch size
  min: 32
  tags:
    - Medium Impact


num_rows:
  type: number
  label: Number of generated samples
  min: 1
  tags:
    - High Impact

data:
  type: object
  label: Training
  fields:
    - dataset

dataset:
  type: object
  label: Training hyper-parameters
  fields:
    - batch_sizes
    - dataset_name

dataset_name:
  type: text
  label: Dataset name
  tags:
    - Low Impact


batch_sizes:
  type: object
  label: Training batch sizes
  fields:
    - stage1#batch-size
    - stage2#batch-size
stage1#batch-size:
  type: number
  label: Batch size (discreted VAE)
  min: 32
  tags:
    - Medium Impact
stage2#batch-size:
  type: number
  label: Batch size (transformer)
  min: 16
  tags:
    - Medium Impact

ts:
  type: object
  label: Data
  fields:
    - static_id
    - other_static_columns
    - sortby

static_id:
  type: select
  options: columns
  label: Column of static ID (data index)
  tags:
    - High Impact
  documentation: |
    The columns that identify the static items, like the customer ID for a customer transaction table.
  required: true
other_static_columns:
  type: select
  multi: true
  options: columns
  label: Non time-series columns
  mutuallyExclusiveFields:
    - ./static_id
  tags:
    - High Impact
sortby:
  type: select
  options: columns
  label: Sort by this column (leave it blank if not applicable)
  mutuallyExclusiveFields:
    - ./static_id
  parseEmptyAsNull: True
  tags:
    - High Impact
  documentation: |
    The column featuring the timeline so that the time-series can be sorted by time. For example, the transaction
    date-time would be the sort by column for transaction records table.

single:
  type: skipped